#!/usr/bin/env bash

mkdir -p logs data
go get -u github.com/moln/{config,loggers,httpextra}
go get -u github.com/gorilla/mux
go get -u code.google.com/p/go.crypto/bcrypt
go get -u github.com/garyburd/redigo/redis
go get -u github.com/nu7hatch/gouuid
go build
foreman start
